### ISSUE TITLE
Allow extending tags, and override test name and description from data

### ISSUE THREAD

**Issue by argos83** [argos83/marvin#10]
Data providers should be able to retrieve meta information from data sources to extend/override a test script info.
E.g. in YAML

```
meta:
   name: New Test name
   description: New test description
   tags: [newtag1, newtag2]
setup_data:
   ...
```
