### ISSUE TITLE
Marvin fails when iteration has no "data" key

### ISSUE THREAD

**Issue by estemendoza** [argos83/marvin#28]
#### Describe your problem
If an iteration doesn't have the "data" key, Marvin fails with a confusing message, like this:
`TypeError: __init__() got an unexpected keyword argument 'test_key'`

#### What command line options do you use?

```
$ marvin test_cases --tags <tag>
```

#### Example of data file

```yaml
setup_data:
iterations:
- test_key: test_value
tear_down_data:
```

### Expected behavior
Marvin should check if there is a "data" key on every iteration and if it's not present, should the proper message and the file where the iteration can be found
